#!/usr/bin/env python3
"""skills.h -> skills seed migration (Phase 4, Task 4.1b).

Extracts the ESkills enum (225 values) from game_share/skills.h and emits
idempotent INSERTs for the `skills` table (DDL lives in 001_sheet_schema.sql).

Derivations (Phase_4_Data_Driven_Mechanics.md, Task 4.1b step 4):
  - branch from the two-letter prefix: SF Combat, SM Magic, SC Crafting,
    SH Foraging (verified against brick usage: fight bricks require SF,
    harvest bricks SH).
  - prerequisites: the parent skill is the ID minus its last letter
    (SCAH -> SCA); the four two-letter roots have none.

Usage: generate_skills_seed.py [--skills-h PATH] [--out FILE]
"""

import argparse
import re
import sys
from pathlib import Path

DEFAULT_SKILLS_H = (Path(__file__).resolve().parents[3]
                    / "ryzomcore/ryzom/common/src/game_share/skills.h")

BRANCHES = {"SF": "Combat", "SM": "Magic", "SC": "Crafting", "SH": "Foraging"}


def parse_enum(text: str) -> list[str]:
    body = re.search(r"enum\s+ESkills.*?\{(.*?)NUM_SKILLS", text, re.S)
    if not body:
        raise SystemExit("ESkills enum not found")
    ids = re.findall(r"^\s*([A-Z][A-Z0-9]*)\s*(?:=\s*\d+\s*)?,", body.group(1), re.M)
    return ids


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--skills-h", type=Path, default=DEFAULT_SKILLS_H)
    ap.add_argument("--out", type=Path, default=None)
    args = ap.parse_args()

    ids = parse_enum(args.skills_h.read_text())
    print(f"-- parsed {len(ids)} skills from {args.skills_h.name}", file=sys.stderr)

    rows = []
    for sid in ids:
        branch = BRANCHES.get(sid[:2])
        if branch is None:
            print(f"-- WARNING: unknown branch prefix for {sid}", file=sys.stderr)
            continue
        prereq = "'{}'" if len(sid) == 2 else "'{" + sid[:-1] + "}'"
        rows.append(f"    ('{sid}', '{sid}', '{branch}', 1, {prereq})")

    sql = (
        "-- 002_skills_seed.sql — GENERATED by tools/skills_to_sql/generate_skills_seed.py\n"
        f"-- from game_share/skills.h ESkills enum ({len(rows)} skills). Do not edit by hand.\n"
        "-- Idempotent: re-running leaves existing rows untouched (cost may be tuned live).\n\n"
        "INSERT INTO skills (id, name, branch, cost, prerequisites) VALUES\n"
        + ",\n".join(rows)
        + "\nON CONFLICT (id) DO NOTHING;\n"
    )
    if args.out:
        args.out.write_text(sql)
        print(f"-- wrote {args.out}", file=sys.stderr)
    else:
        print(sql)


if __name__ == "__main__":
    main()
