#!/usr/bin/env python3
"""Task 4.2c Step 1 — import binary character save files into PostgreSQL.

Enumerates ``account_<uid>_<slot>_pdr.bin`` files under --saves-dir, converts
each one with the save_to_json bridge tool (ryzom/tools/save_to_json — walks
the CPersistentDataRecord token stream and prints a JSON tree), extracts the
character metadata fields, and upserts rows into the ``characters`` table
keyed on (account_id, slot) so re-runs are idempotent.

Usage:
  migrate_saves.py --saves-dir <dir> --dry-run                # print rows
  migrate_saves.py --saves-dir <dir> --db-url postgres://...  # direct upsert
  migrate_saves.py --saves-dir <dir> --sql-out saves.sql      # SQL for psql
                                # (no psycopg2 needed; pipe into docker psql)

The bridge tool needs sheet_id.bin on its search path (--sheet-id-path).
"""

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

SAVE_RE = re.compile(r"^account_(\d+)_(\d+)_pdr\.bin$")

# CCharacter PDR: _Gender is GSGENDER::EGender (uint8)
GENDER = {"0": "male", "1": "female", "2": "neutral"}


def find_field(nodes, name):
    """First leaf value with the given token name, walking nested PDR nodes."""
    for node in nodes:
        if node.get("n") == name and "v" in node:
            return node["v"]
        children = node.get("c")
        if isinstance(children, list):
            value = find_field(children, name)
            if value is not None:
                return value
    return None


def convert(tool, sheet_id_path, path):
    cmd = [str(tool)]
    if sheet_id_path:
        cmd.append("-s" + str(sheet_id_path))
    cmd.append(str(path))
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        raise RuntimeError(proc.stderr.strip().splitlines()[-1] if proc.stderr.strip() else f"exit {proc.returncode}")
    # the JSON document is the stdout line starting with {"file" — be
    # defensive about any stray library output around it
    for line in proc.stdout.splitlines():
        if line.startswith('{"file"'):
            return json.loads(line)
    raise RuntimeError("no JSON document on stdout")


def collect_rows(args):
    saves_dir = Path(args.saves_dir)
    rows = []
    failures = 0
    files = sorted(p for p in saves_dir.rglob("account_*_pdr.bin") if SAVE_RE.match(p.name))
    if not files:
        print(f"warning: no account_*_*_pdr.bin files under {saves_dir}", file=sys.stderr)

    for path in files:
        m = SAVE_RE.match(path.name)
        account_id, slot = m.group(1), int(m.group(2))
        try:
            doc = convert(args.tool, args.sheet_id_path, path)
        except (RuntimeError, json.JSONDecodeError) as exc:
            print(f"FAIL {path.name}: {exc}", file=sys.stderr)
            failures += 1
            continue

        root = doc.get("root", [])
        name = find_field(root, "_Name")
        if not name:
            print(f"FAIL {path.name}: no _Name token (not a character save?)", file=sys.stderr)
            failures += 1
            continue

        race = (find_field(root, "_Race") or "unknown").lower()
        gender_raw = find_field(root, "_Gender")
        gender = GENDER.get(gender_raw or "", None)
        if gender is None:
            print(f"warning: {path.name}: unexpected _Gender {gender_raw!r} -> 'neutral'", file=sys.stderr)
            gender = "neutral"

        rows.append({
            "account_id": account_id,
            "slot": slot,
            "name": name,
            "race": race,
            "gender": gender,
            "source_file": path.name,
        })

    return rows, len(files), failures


UPSERT_SQL = """
INSERT INTO characters (account_id, slot, name, race, gender, source_file, imported_at)
VALUES (%(account_id)s, %(slot)s, %(name)s, %(race)s, %(gender)s, %(source_file)s, NOW())
ON CONFLICT (account_id, slot) DO UPDATE SET
    name = EXCLUDED.name,
    race = EXCLUDED.race,
    gender = EXCLUDED.gender,
    source_file = EXCLUDED.source_file,
    imported_at = EXCLUDED.imported_at
"""


def sql_quote(value):
    return "'" + str(value).replace("'", "''") + "'"


def write_sql(rows, out):
    out.write("-- generated by migrate_saves.py (Task 4.2c Step 1)\n")
    out.write("BEGIN;\n")
    for row in rows:
        out.write(
            "INSERT INTO characters (account_id, slot, name, race, gender, source_file, imported_at)\n"
            f"VALUES ({sql_quote(row['account_id'])}, {row['slot']}, {sql_quote(row['name'])}, "
            f"{sql_quote(row['race'])}, {sql_quote(row['gender'])}, {sql_quote(row['source_file'])}, NOW())\n"
            "ON CONFLICT (account_id, slot) DO UPDATE SET\n"
            "    name = EXCLUDED.name, race = EXCLUDED.race, gender = EXCLUDED.gender,\n"
            "    source_file = EXCLUDED.source_file, imported_at = EXCLUDED.imported_at;\n"
        )
    out.write("COMMIT;\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--saves-dir", required=True, help="directory containing account_*_*_pdr.bin files (searched recursively)")
    parser.add_argument("--tool", default="../ryzomcore/build/ryzom/bin/Debug/save_to_json", help="path to the save_to_json bridge binary")
    parser.add_argument("--sheet-id-path", default="../ryzomcore/build/ryzom/bin/Debug", help="directory containing sheet_id.bin")
    parser.add_argument("--db-url", help="PostgreSQL DSN for direct upsert (psycopg2)")
    parser.add_argument("--sql-out", help="write upsert SQL to this file instead of connecting (no psycopg2 needed)")
    parser.add_argument("--dry-run", action="store_true", help="print rows instead of writing to the database")
    args = parser.parse_args()

    if not args.dry_run and not args.db_url and not args.sql_out:
        parser.error("one of --dry-run, --db-url or --sql-out is required")
    if not Path(args.tool).is_file():
        parser.error(f"bridge tool not found: {args.tool}")

    rows, total, failures = collect_rows(args)

    if args.dry_run:
        for row in rows:
            print(json.dumps(row))
    elif args.sql_out:
        with open(args.sql_out, "w") as out:
            write_sql(rows, out)
    else:
        import psycopg2  # deferred: only needed for direct upsert
        conn = psycopg2.connect(args.db_url)
        with conn, conn.cursor() as cur:
            for row in rows:
                cur.execute(UPSERT_SQL, row)
        conn.close()

    print(f"{len(rows)} of {total} save files imported, {failures} failed", file=sys.stderr)
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
