-- 001_sheet_schema.sql — Phase 4, Task 4.1a (D1)
--
-- Game-data sheet schema for PostgreSQL, replacing the binary sheet system
-- (ADR-005). Generated by tools/dfn_to_sql/generate_schema.py from the
-- 422 DFN + 231 TYP files in ryzomcore_leveldesign, then hand-tuned:
--
--   * items: core fields promoted out of the _item_basics sub-DFN into real
--     columns (Investigation 5 recommended pattern); the single type-specific
--     sub-DFN block (armor / melee weapon / ...) lives in `extras`.
--   * creatures: attack_list0..7 columns folded into creature_attack_lists;
--     the four melee/range/nuke/heal _cfg array junctions merged into
--     creature_action_configs; default_stats added for the GM dashboard
--     "Revert to factory stats" feature.
--   * npc_loot_tables: flattens creature -> *.loot_table -> _loot_table_row
--     (item, min, max, chance) into one relational table (D1 shape).
--   * bricks: schema specified in Task 4.1b (populated by Task 4.1c from the
--     625 .sbrick files).
--   * characters: schema specified in Task 4.2c (populated by the save
--     migration, not by sheet data).
--
-- Idempotent: every statement is IF NOT EXISTS or duplicate-tolerant, so the
-- file can be re-applied safely.
--
-- MySQL remains authoritative for login/auth (nel_login) — do NOT add
-- account tables here (ADR-005).

-- ---------------------------------------------------------------------------
-- Enum types (from item_family.typ, item_type.typ, item_origine.typ)
-- ---------------------------------------------------------------------------

DO $$ BEGIN
    CREATE TYPE item_family_enum AS ENUM ('UNDEFINED', 'ARMOR', 'MELEE_WEAPON', 'RANGE_WEAPON', 'SHIELD', 'AMMO', 'CRAFTING_TOOL', 'HARVEST_TOOL', 'TAMING_TOOL', 'TRAINING_TOOL', 'CORPSE', 'CARRION', 'BAG', 'STACK', 'RAW_MATERIAL', 'FOOD', 'JEWELRY', 'TELEPORT', 'LIVING_SEED', 'LITTLE_SEED', 'MEDIUM_SEED', 'BIG_SEED', 'VERY_BIG_SEED', 'MISSION_ITEM', 'CRYSTALLIZED_SPELL', 'ITEM_SAP_RECHARGE', 'PET_ANIMAL_TICKET', 'GUILD_OPTION', 'HANDLED_ITEM', 'COSMETIC', 'SERVICE', 'CONSUMABLE', 'XP_CATALYSER', 'SCROLL', 'SCROLL_R2', 'COMMAND_TICKET', 'GENERIC_ITEM');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE item_type_enum AS ENUM ('UNDEFINED', 'DAGGER', 'SWORD', 'MACE', 'AXE', 'SPEAR', 'STAFF', 'MAGICIAN_STAFF', 'TWO_HAND_SWORD', 'TWO_HAND_AXE', 'PIKE', 'TWO_HAND_MACE', 'AUTOLAUCH', 'BOWRIFLE', 'LAUNCHER', 'PISTOL', 'BOWPISTOL', 'RIFLE', 'HARPOON', 'AUTOLAUNCH_AMMO', 'BOWRIFLE_AMMO', 'GRENADE_AMMO', 'LAUNCHER_AMMO', 'PISTOL_AMMO', 'BOWPISTOL_AMMO', 'RIFLE_AMMO', 'HARPOON_AMMO', 'SHIELD', 'BUCKLER', 'LIGHT_BOOTS', 'LIGHT_GLOVES', 'LIGHT_PANTS', 'LIGHT_SLEEVES', 'LIGHT_VEST', 'MEDIUM_BOOTS', 'MEDIUM_GLOVES', 'MEDIUM_PANTS', 'MEDIUM_SLEEVES', 'MEDIUM_VEST', 'HEAVY_BOOTS', 'HEAVY_GLOVES', 'HEAVY_PANTS', 'HEAVY_SLEEVES', 'HEAVY_VEST', 'HEAVY_HELMET', 'ANKLET', 'BRACELET', 'DIADEM', 'EARING', 'PENDANT', 'RING', 'SHEARS', 'ArmorTool', 'AmmoTool', 'MeleeWeaponTool', 'RangeWeaponTool', 'JewelryTool', 'CAMPSFIRE', 'MEKTOUB_PACKER_TICKET', 'MEKTOUB_MOUNT_TICKET', 'FOOD', 'TATOO_MALE', 'HAIR_MALE', 'HAIRCOLOR_MALE', 'TATOO_FEMALE', 'HAIR_FEMALE', 'HAIRCOLOR_FEMALE', 'SERVICE_STABLE', 'LIGHT_HELMET', 'ToolMaker', 'JOB_ELEMENT', 'GENERIC');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE item_origin_enum AS ENUM ('Common', 'Fyros', 'Matis', 'Tryker', 'Zorai', 'Tribe', 'Karavan', 'Refugee', 'Kami');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ---------------------------------------------------------------------------
-- items — one row per .sitem sheet. Core columns from _item_basics.dfn;
-- the type-specific sub-DFN block (armor stats, weapon damage, ...) goes in
-- `extras` keyed by sub-DFN name, e.g. {"armor": {...}}.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS items (
    id              TEXT PRIMARY KEY,           -- sheet filename without extension
    name            TEXT,
    origin          item_origin_enum DEFAULT 'Common',
    family          item_family_enum DEFAULT 'UNDEFINED',
    item_type       item_type_enum   DEFAULT 'UNDEFINED',
    stackable       INTEGER DEFAULT 1,
    quality         INTEGER DEFAULT 0,
    bulk            REAL    DEFAULT 0,
    weight          REAL    DEFAULT 0,
    saleable        BOOLEAN DEFAULT TRUE,
    drop_or_sell    BOOLEAN DEFAULT TRUE,
    price           REAL    DEFAULT 0,
    consumable      BOOLEAN DEFAULT FALSE,
    craft_plan      TEXT,                       -- sheet ref *.sbrick
    req_skill       TEXT,                       -- _Skills.typ enum value; FK to skills once Task 4.1b lands
    req_skill_min   INTEGER DEFAULT 0,
    req_skill2      TEXT,
    req_skill2_min  INTEGER DEFAULT 0,
    extras          JSONB DEFAULT '{}'          -- type-specific sub-DFN block + unmapped basics fields
);

CREATE INDEX IF NOT EXISTS items_family_idx ON items (family);
CREATE INDEX IF NOT EXISTS items_item_type_idx ON items (item_type);

-- EAV side-table for tunable numeric stats (D1 `item_stats`). Live balance
-- edits target this table without schema changes.
CREATE TABLE IF NOT EXISTS item_stats (
    item_id         TEXT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
    stat_key        TEXT NOT NULL,
    base_value      REAL DEFAULT 0,
    quality_factor  REAL DEFAULT 0,
    PRIMARY KEY (item_id, stat_key)
);

-- ---------------------------------------------------------------------------
-- creatures — one row per .creature sheet. Scalar top-level DFN fields are
-- real columns; each sub-DFN block is its own JSONB column (creature.dfn
-- composition). default_stats backs the GM dashboard "Revert to factory
-- stats" feature.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS creatures (
    id              TEXT PRIMARY KEY,           -- sheet filename without extension
    alias           TEXT,
    category        TEXT,
    race_code       TEXT,
    group_id        TEXT,
    group_assist    TEXT,
    group_attack    TEXT,
    creature_level  REAL,
    r2_npc          BOOLEAN DEFAULT FALSE,
    action_cfg      TEXT DEFAULT '1111f',
    action_on_death TEXT,                       -- sheet ref *.aiaction
    item_right      TEXT,                       -- sheet ref *.sitem
    item_right_stat TEXT,                       -- sheet ref *.itemstat
    item_left       TEXT,                       -- sheet ref *.sitem
    item_left_stat  TEXT,                       -- sheet ref *.itemstat
    basics          JSONB DEFAULT '{}',         -- _creature_basics.dfn (level, race, life, regen, ...)
    model_3d        JSONB DEFAULT '{}',         -- _creature_3d.dfn
    loot            JSONB DEFAULT '{}',         -- _creature_loot.dfn (raw; relational form in npc_loot_tables)
    harvest         JSONB DEFAULT '{}',         -- _creature_harvest.dfn
    collision       JSONB DEFAULT '{}',         -- _creature_collision.dfn
    properties      JSONB DEFAULT '{}',         -- _creature_properties.dfn
    action_phrases  JSONB DEFAULT '{}',         -- _creature_phrases.dfn
    shopkeeper      JSONB DEFAULT '{}',         -- _creature_shopkeeper_type.dfn
    combat          JSONB DEFAULT '{}',         -- _creature_combat.dfn
    text_ids        JSONB DEFAULT '{}',         -- _creature_text_id.dfn
    protections     JSONB DEFAULT '{}',         -- _protections.dfn
    resists         JSONB DEFAULT '{}',         -- _creature_resists.dfn
    damage_shield   JSONB DEFAULT '{}',         -- _creature_damage_shield.dfn
    localisation    JSONB DEFAULT '{}',         -- body_to_bone.dfn (hit localisation)
    animal_bag      JSONB DEFAULT '{}',         -- _creature_bag.dfn
    special_comp    JSONB DEFAULT '[]',         -- special_comp string array
    alt_clothes     JSONB DEFAULT '[]',         -- Basics "Alternative Clothes" *.creature refs
    extras          JSONB DEFAULT '{}',         -- anything unmapped by the migration script
    default_stats   JSONB DEFAULT '{}'          -- factory snapshot for "Revert to factory stats"
);

CREATE INDEX IF NOT EXISTS creatures_category_idx ON creatures (category);
CREATE INDEX IF NOT EXISTS creatures_race_code_idx ON creatures (race_code);

-- attack_list0..attack_list7 from creature.dfn — meaningful relational
-- structure, kept as a junction table (Task 4.1a hand-tune note).
CREATE TABLE IF NOT EXISTS creature_attack_lists (
    creature_id     TEXT NOT NULL REFERENCES creatures(id) ON DELETE CASCADE,
    slot            INTEGER NOT NULL CHECK (slot BETWEEN 0 AND 7),
    attack_list     TEXT NOT NULL,              -- sheet ref *.attack_list
    PRIMARY KEY (creature_id, slot)
);

-- melee_cfg / range_cfg / nuke_cfg / heal_cfg Array="true" fields from
-- creature.dfn, merged into one junction keyed by action type.
CREATE TABLE IF NOT EXISTS creature_action_configs (
    creature_id     TEXT NOT NULL REFERENCES creatures(id) ON DELETE CASCADE,
    action_type     TEXT NOT NULL CHECK (action_type IN ('melee', 'range', 'nuke', 'heal')),
    ordinal         INTEGER NOT NULL,
    actionlist      TEXT NOT NULL,              -- sheet ref *.actionlist
    PRIMARY KEY (creature_id, action_type, ordinal)
);

-- Flattened loot: creature.dfn -> Loot Tables (*.loot_table, Array) ->
-- _loot_table_row.dfn (item, min, max, chance). item_id is intentionally NOT
-- a foreign key — loot rows can reference sheets excluded from the import.
CREATE TABLE IF NOT EXISTS npc_loot_tables (
    npc_id          TEXT NOT NULL REFERENCES creatures(id) ON DELETE CASCADE,
    item_id         TEXT NOT NULL,
    drop_rate       REAL DEFAULT 0,             -- _loot_table_row chance
    min_qty         INTEGER DEFAULT 1,
    max_qty         INTEGER DEFAULT 1,
    PRIMARY KEY (npc_id, item_id)
);

-- ---------------------------------------------------------------------------
-- bricks — one row per .sbrick sheet (625 files). Schema from Task 4.1b;
-- populated by the Task 4.1c migration script. The Sheet API serves these
-- for the phrase composer and /phrase/validate.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS bricks (
    id           TEXT PRIMARY KEY,  -- sbrick sheet ID (e.g. "baka01")
    family       TEXT,              -- 'Combat', 'Magic', 'Craft', 'Forage'
    brick_type   TEXT,              -- 'Mandatory', 'Optional', 'Parameter', 'Credit'
    skill_req    TEXT,
    skill_min    INTEGER DEFAULT 0,
    sap_cost     INTEGER DEFAULT 0,
    hp_cost      INTEGER DEFAULT 0,
    sta_cost     INTEGER DEFAULT 0,
    description  TEXT,
    extras       JSONB DEFAULT '{}'
);

CREATE INDEX IF NOT EXISTS bricks_family_idx ON bricks (family);

-- ---------------------------------------------------------------------------
-- skills — the 225-value ESkills enum from game_share/skills.h (not a DFN).
-- Seeded by migrations/002_skills_seed.sql (generated by
-- tools/skills_to_sql/generate_skills_seed.py). Tree layout is computed by
-- the client from the ID naming convention — deliberately no ui_pos column.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS skills (
    id            TEXT PRIMARY KEY,    -- enum value (e.g. "SCAH")
    name          TEXT,                -- enum name (human names live in translation files)
    branch        TEXT,                -- Combat | Magic | Crafting | Foraging (SF/SM/SC/SH prefix)
    cost          INTEGER DEFAULT 1,
    prerequisites TEXT[] DEFAULT '{}'  -- parent ID by prefix, empty for the 4 roots
);

CREATE INDEX IF NOT EXISTS skills_branch_idx ON skills (branch);

-- ---------------------------------------------------------------------------
-- characters — schema from Task 4.2c (Finding D). Populated by the binary
-- save migration, then dual-written by the EGS. Not sheet data; lives here
-- because D1 requires the full table set in one versioned migration.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS characters (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    account_id      TEXT NOT NULL,        -- nel_login.accounts (MySQL)
    egs_entity_id   BIGINT,               -- EGS numeric entity ID; NULL until first login post-migration
    name            TEXT NOT NULL,
    race            TEXT NOT NULL,        -- 'fyros' | 'matis' | 'zorai' | 'tryker'
    gender          TEXT NOT NULL,        -- 'male' | 'female'
    is_gm_character BOOLEAN DEFAULT FALSE,
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    last_login_at   TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS characters_account_id_idx ON characters (account_id);
CREATE INDEX IF NOT EXISTS characters_egs_entity_id_idx ON characters (egs_entity_id);
