package questc

import (
	"fmt"
	"strconv"
	"strings"
)

// Compile validates the storyline and emits a Lua scenario script. The script
// registers the storyline against the quest_runtime module (scenarios/
// quest_runtime.lua) and returns the storyline object, so it can be `dofile`d
// or `require`d by the EGS Lua runtime / dynamic_scenario_service.
func Compile(s *Storyline) (string, error) {
	if err := s.Validate(); err != nil {
		return "", err
	}
	var b strings.Builder
	fmt.Fprintf(&b, "-- Code generated by quest-compiler from %s. DO NOT EDIT.\n", SchemaVersion)
	fmt.Fprintf(&b, "-- Storyline: %s (%s)\n", s.Name, s.ID)
	b.WriteString("local quest = require(\"quest_runtime\")\n\n")
	fmt.Fprintf(&b, "local story = quest.new_storyline({ id = %s, name = %s })\n\n",
		luaStr(s.ID), luaStr(s.Name))

	for _, q := range s.Quests {
		emitQuest(&b, q)
	}

	start := s.StartQuest
	if start == "" {
		start = s.Quests[0].ID
	}
	fmt.Fprintf(&b, "story:set_start(%s)\n", luaStr(start))
	b.WriteString("return story\n")
	return b.String(), nil
}

func emitQuest(b *strings.Builder, q Quest) {
	b.WriteString("story:add_quest({\n")
	fmt.Fprintf(b, "  id = %s,\n", luaStr(q.ID))
	fmt.Fprintf(b, "  name = %s,\n", luaStr(q.Name))
	if q.Start != nil {
		fmt.Fprintf(b, "  start = %s,\n", triggerLit(*q.Start))
	}
	b.WriteString("  objectives = {\n")
	for _, o := range q.Objectives {
		emitObjective(b, o)
	}
	b.WriteString("  },\n")
	b.WriteString("})\n\n")
}

func emitObjective(b *strings.Builder, o Objective) {
	b.WriteString("    {\n")
	fmt.Fprintf(b, "      id = %s,\n", luaStr(o.ID))
	if o.Text != "" {
		fmt.Fprintf(b, "      text = %s,\n", luaStr(o.Text))
	}
	fmt.Fprintf(b, "      trigger = %s,\n", triggerLit(o.Trigger))
	if len(o.Consequences) > 0 {
		b.WriteString("      consequences = {\n")
		for _, c := range o.Consequences {
			fmt.Fprintf(b, "        %s,\n", consequenceLit(c))
		}
		b.WriteString("      },\n")
	}
	if o.Choice != nil {
		emitChoice(b, *o.Choice)
	}
	b.WriteString("    },\n")
}

func emitChoice(b *strings.Builder, c Choice) {
	b.WriteString("      choice = {\n")
	fmt.Fprintf(b, "        prompt = %s,\n", luaStr(c.Prompt))
	if c.Mode != "" {
		fmt.Fprintf(b, "        mode = %s,\n", luaStr(c.Mode))
	}
	b.WriteString("        options = {\n")
	for _, opt := range c.Options {
		var parts []string
		parts = append(parts, "id = "+luaStr(opt.ID))
		parts = append(parts, "text = "+luaStr(opt.Text))
		if opt.NextQuest != "" {
			parts = append(parts, "next_quest = "+luaStr(opt.NextQuest))
		}
		fmt.Fprintf(b, "          { %s },\n", strings.Join(parts, ", "))
	}
	b.WriteString("        },\n")
	b.WriteString("      },\n")
}

// triggerLit renders a trigger as an inline Lua table with only its set fields.
func triggerLit(t Trigger) string {
	parts := []string{"on = " + luaStr(t.On)}
	if t.NPC != "" {
		parts = append(parts, "npc = "+luaStr(t.NPC))
	}
	if t.Creature != "" {
		parts = append(parts, "creature = "+luaStr(t.Creature))
	}
	if t.Item != "" {
		parts = append(parts, "item = "+luaStr(t.Item))
	}
	if t.Zone != "" {
		parts = append(parts, "zone = "+luaStr(t.Zone))
	}
	if t.Count != 0 {
		parts = append(parts, "count = "+strconv.Itoa(t.Count))
	}
	if t.X != 0 {
		parts = append(parts, "x = "+numLit(t.X))
	}
	if t.Y != 0 {
		parts = append(parts, "y = "+numLit(t.Y))
	}
	if t.Radius != 0 {
		parts = append(parts, "radius = "+numLit(t.Radius))
	}
	if t.Seconds != 0 {
		parts = append(parts, "seconds = "+strconv.Itoa(t.Seconds))
	}
	return "{ " + strings.Join(parts, ", ") + " }"
}

func consequenceLit(c Consequence) string {
	parts := []string{"action = " + luaStr(c.Action)}
	if c.Creature != "" {
		parts = append(parts, "creature = "+luaStr(c.Creature))
	}
	if c.Item != "" {
		parts = append(parts, "item = "+luaStr(c.Item))
	}
	if c.Count != 0 {
		parts = append(parts, "count = "+strconv.Itoa(c.Count))
	}
	if c.Amount != 0 {
		parts = append(parts, "amount = "+strconv.Itoa(c.Amount))
	}
	if c.Faction != "" {
		parts = append(parts, "faction = "+luaStr(c.Faction))
	}
	if c.Flag != "" {
		parts = append(parts, "flag = "+luaStr(c.Flag))
	}
	if c.Value != "" {
		parts = append(parts, "value = "+luaStr(c.Value))
	}
	if c.Text != "" {
		parts = append(parts, "text = "+luaStr(c.Text))
	}
	return "{ " + strings.Join(parts, ", ") + " }"
}

// numLit prints a float as an integer when it has no fractional part, so
// coordinates read as 1000 rather than 1000.0.
func numLit(f float64) string {
	if f == float64(int64(f)) {
		return strconv.FormatInt(int64(f), 10)
	}
	return strconv.FormatFloat(f, 'g', -1, 64)
}

// luaStr returns a safe double-quoted Lua string literal.
func luaStr(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}
